### ISSUE TITLE
Segmentation Fault 

### ISSUE THREAD

**Issue by Github-By-G** [Nadharm/CoVirt#1]
i had setup everything correclty but 'm getting "`segmentation Fault`"  while running insmod ./covirt_module.ko !!

![image](https://github.com/Nadharm/CoVirt/assets/83700543/8d93efa5-3d80-4644-8ebc-88e56ea06f98)

- am using ubuntu 22.04 host machine-> but its intel based gen (is it due to that?)
- also i tried with 21.10 version aswell

**Comment by Nadharm** [comment]
Hi!

This project will only work with AMD cpus w/ SVM support. IIRC, Intel's VTx and AMD's SVM implementations are incompatible. For example, to enable SVM, you would set the [EFER_MSR's SVME bit](https://github.com/Nadharm/CoVirt/blob/773246827eedf07cdfcb573bc0155a14cbb29c65/covirt/src/svm_utils.c#L99), but to enable Intel's VMX, you would set the CR4.VMXE bit (Reference Volume 3, Section 24.7 [Intel Manual](https://cdrdv2.intel.com/v1/dl/getContent/671200)). 

While I don't intend on cleaning up or maintaining this project (thus it may remain an eternal and public reminder of my poor/lazy coding practices), perhaps you could modify your "test.sh" to use this:

`qemu-system-x86_64 -cpu host,-x2apic -enable-kvm -m 2048 -smp 1 -kernel $PLAY/obj/linux-basic/arch/x86_64/boot/bzImage -initrd obj/initramfs-busybox.cpio.gz -s -append "console=ttyS0 nokaslr" -nographic`

instead of the current qemu command if you want to capture more output (just uncomment [this guy](https://github.com/Nadharm/CoVirt/blob/773246827eedf07cdfcb573bc0155a14cbb29c65/covirt/test.sh#L26)). I _think_ that you should be able to see some of the DEBUG_PRINT statements in [svm_check](https://github.com/Nadharm/CoVirt/blob/773246827eedf07cdfcb573bc0155a14cbb29c65/covirt/src/svm_utils.c#L18) being outputted to your console.
